# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HTUKpTIqnMDs5Vua8PzTjc6RXxR+VHp4t/9ECRjmwkVQjrMI7XYQ1moE9LKEfDzD8x1rJybgk9SvWTuAN87pVJaezF5cjKCOvKi5lRzwYP68cN1yVGeqrr3kKcRwf80YBXPsNcjuIzHuqVvEvZ6i+zqAsEvvkok7t1weqaMSNI+jJFVzsVpYd4+kjRcqJmV9sVQiAPu5NI+D957es2QCAVGD5adtvl6dcvWN/8XOE36INUoCnJhmngZaz2XydAM6cqwprvnPYKS4NDTidXIO5LReYt5DlClfwLmOYHhFRLL/Ley4u7Nviz3QELLFcqOvJzkcnnNX1/CRx9afo6bw2fABMSUpYfIjxV1er++R/L4zSgrkahr1ywB322+OacAFCnqoWvxPm/nZwY+P3i9wj/C0s3rJV9Z0biCED5rSGnrnvAGzi89CCFSEXb8b297xBdjMjOcs3kIYAj3a/T1/FJAs5Fy9u6AJEI4OoJBZp1i24APlEE7CVq+NT20qr/9bvZfMqxVUxEr1NxbDl5/b39i9Yj5WuwTFSrb4w2pr3vVklSPXx331LDfJ+ku2+JMjLF4Lhr9Sxc/T0CpTp0VfGnfgHJhct3SZmJhDCBX9knBliYx5gNtvwidLrNysL/f+YvtB7l3V0nXRRkx3D7RshPSXUyjENWrR0XcgRVEhPg8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
