travis:
  secure:
    BINSTAR_TOKEN: KQHUrFkRH0szLNB6X+n7rMiQeezhMNhvRjAiaMitGRS3R93WFgNFZEnQLBEbjIcwLtDIalBCJ9g6i4N+IJUfT+wJxh7He9wypphkwSDGyhgLpWaozW1UeOTMRWaVW1CFbv+BsJbi9JLslvnL8N1ORu0TTeC9SZVwk3Qd/zbd1K3QvJGIHAWhOESMnsnTTTb+KWV6G4wKmaLbYHAIs8ge5PzMRQ4W832wXUiDuf3SOnzYivSKyoTm4UY4HWsjgGIYI0cvoRyVV2Vptu6ezctRRmbMboPBq2BNL86iBeBr0zWY3BfoxSZ83mt11mt/uOwIeSjWmXZS1w3hexTbP6AAcqXryHOHe7owAZJN0fMVfZj7MB8dMDGeKObU2s9mOEmddB9N3ZHVM+Z6calks/xPbPIWyE/XD8jl3AP1IDR8QFMHJj/Q5Nsn6NHy6SRhXqulpQcqQqCGpznIobpv7qnaUcvF9hNYIudY8hGHhdWSAmPi/6eNHbIaNlvjMt4pOoy0CeXUjK823ccEH2a0rh1sKp4OwVXnoVLns0pkws5FdYfcIcFSt3mO1Ie+In/AsKOsPbnn3+jDVVkw8C5gAWd+bNoV2OqQr4bzYpDN7wQQFOCT0KGjwWN1HnppHfeO23XTSAeJgqw6Zq8ABezZ3QyQUjN+oyDTyYPKPvqOwHbOfn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
